ninety-nine-cats/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"


  resources :cats, only: [:index, :create, :show, :new, :edit, :update]
  
end

ninety-nine-cats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

ninety-nine-cats/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :bigint           not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Cat < ApplicationRecord
    CAT_COLORS = ['white', 'black', 'brown', 'orange', 'blue']
    validates :name, presence: true
    validates :color, presence: true, inclusion: {in: CAT_COLORS}
    validates :sex, presence: true, inclusion: {in: ['M','F']}
    validate :birth_date_cannot_be_future

    def birth_date_cannot_be_future
        if birth_date && birth_date > Date.today
            errors.add(:birth_date, "Can't be in future!")
        end
    end

    def age
        now = Date.today
        age = now.year - birth_date.year

        age -= 1 if now < birth_date + age.years
        age 
    end
end

ninety-nine-cats/app/models/cat_rental_request.rb
class CatRentalRequest < ApplicationRecord
end

ninety-nine-cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

ninety-nine-cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController

    def index
        @cats = Cat.all
        render :index
        # render json: @cats
    end

    def show
        @cat = Cat.find_by(id: params[:id])
        render :show
        # render json: @cat
    end

    def create
        # debugger
        @cat = Cat.new(cat_params)

        if @cat&.save
            render :show
            # render json: @cat
        else
            render :new
            # render json: ['did not work']
        end
    end

    def update
        @cat = Cat.find_by(id: params[:id])
        if @cat.update(cat_params)
            render :show
            # render json: @cat

        else
            render :edit
            # render json: ['did not work']
        end
    end

    def new
        @cat = Cat.new
        render :new
    end

    def edit
        @cat = Cat.find_by(id: params[:id])
        render :edit
    end


    private
    def cat_params
        params.require(:cat).permit(:birth_date, :name, :color, :sex, :description)
    end
end

ninety-nine-cats/app/helpers/application_helper.rb
module ApplicationHelper
end

ninety-nine-cats/app/helpers/cats_helper.rb
module CatsHelper
end

ninety-nine-cats/app/views/cats/_cat.html.erb
<table>
    <thead>
        <tr>
            <th colspan="2"><%= cat.name%></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Attribute:</td>
            <td>Value</td>
        </tr>
        <tr>
            <td>Birth Date:</td>
            <td><%= cat.birth_date%></td>
        </tr>
        <tr>
            <td>Color:</td>
            <td><%= cat.color%></td>
        </tr>
        <tr>
            <td>Age:</td>
            <td><%= cat.age%></td>
        </tr>
        <tr>
            <td>Sex:</td>
            <td><%= cat.sex%></td>
        </tr>
        <tr>
            <td>Description:</td>
            <td>"<%= cat.description %>"</td>
        </tr>
    </tbody>
</table>
<p><a href="<%= cats_url %>">Back to all cats page</a></p>

ninety-nine-cats/app/views/cats/_form.html.erb
<% if type == 'new' %>
    <% action_url = cats_url %>
    <% button_text = 'Create Cat'%>
<% else %>
    <% action_url = cat_url(cat) %>
    <% button_text = 'Update Cat'%>
<% end %>


<form action="<%=action_url %>" method="POST">
    <% if type == 'edit' %>
    <input type="hidden" name="_method" value="PATCH">
    <% end %>

    <label for="birth_date">Birth Date: </label>
    <input id = 'birth_date' type="date" name = 'cat[birth_date]' value="<%=cat.birth_date%>"/>

    <label for="color">Color: </label>
    <input id = 'color' type="text" name = 'cat[color]' value="<%=cat.color%>"/>

    <label for="name">Name: </label>
    <input id = 'name' type="text" name = 'cat[name]' value="<%=cat.name%>"/>

    <label for="sex">Sex: </label>
    <input id = 'sex' type="text" name = 'cat[sex]' value="<%=cat.sex%>"/>

    <label for="description">Description: </label>
    <input id = 'description' type="text" name = 'cat[description]' value="<%=cat.description%>"/>

    <input type="submit" value="<%=button_text%>" />
</form>

ninety-nine-cats/app/views/cats/edit.html.erb
<%= render 'form', cat: @cat, type: 'edit'%>

ninety-nine-cats/app/views/cats/index.html.erb
<h1>All the cats in the world! </h1>
<%@cats.each do |cat|%>
    <p><%= cat.name%></p>
    <ul> 
        <li><%= cat.birth_date%></li>
        <li><%= cat.color%></li>
        <li><%= cat.sex%></li>
        <li><%= cat.description%></li>
        <li><a href="<%= cat_url(cat) %>">Inspect cat</a> </li>
    </ul>
 <%end%>

ninety-nine-cats/app/views/cats/new.html.erb
<%= render 'form', cat: @cat, type: 'new'%>

ninety-nine-cats/app/views/cats/show.html.erb
<%= render 'cat', cat: @cat, type: 'show'%>

<a href="<%= edit_cat_url(@cat) %>">Update Cat</a>

ninety-nine-cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinetyNineCats</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>